package employee;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import javax.swing.*;

public class Enroll extends JFrame{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Enroll(){
	
	JFrame f;
	JLabel l,l1,l2,l3,l4,l5,l6,l7,l8;
	JTextField t1,t3,t4,t5,t6,t7;
	JButton b,b1,b2;
		f=new JFrame(" ENROLL ");	
		 f.setLayout(null);
		 f.setBounds(400,150,900,700);
		 
		 l6=new JLabel();
	        l6.setBounds(0,0,900,700);
	        l6.setLayout(null);
	        f.getContentPane().setBackground(Color.GREEN);
	        
		 l = new JLabel("Enter New Employee Details");
	        l.setBounds(280,30,500,50);
	        l.setFont(new Font("Arial",Font.PLAIN,25));
	        l.setForeground(Color.black);
	        l6.add(l);
	        f.add(l6);
		 
		 
		 
		 l1=new JLabel("Name");
		 t1=new JTextField();
		 l1.setBounds(50,150,100,30);
	     t1.setBounds(200,150,150,30);
	     l1.setFont(new Font("Cambria",Font.BOLD,20));
	     l6.add(l1);
	     l6.add(t1);
	      
		 
		 l2=new JLabel("** ID gets generated by the System itself **");
		l2.setBounds(240,570,900,30);
	        
	        l2.setFont(new Font("Segoe UI Black",Font.ITALIC,20));
	        IDgen i=new IDgen();
	        String r=i.IDgeN(5);     //This function itself generates a random ID  of length 5 
	        l6.add(l2);
	       
	        
	     l3=new JLabel("Position");
	     l3.setBounds(400,150,200,30);

	        t3=new JTextField();
	        t3.setBounds(600,150,150,30);
	        l3.setFont(new Font("Cambria",Font.BOLD,20));
	        l6.add(l3);
	        l6.add(t3);
	      
	     l4=new JLabel("Salary");
	     l4.setBounds(50,230,100,30);
	       
	        t4=new JTextField();
	        t4.setBounds(200,230,150,30);
	        l4.setFont(new Font("Cambria",Font.BOLD,20));
	        l6.add(l4);
	        l6.add(t4);
	        
	     l5=new JLabel("Department");
	     l5.setBounds(400,300,120,30);
	        
	        t5=new JTextField();
	        t5.setBounds(600,300,150,30);
	        l5.setFont(new Font("Cambria",Font.BOLD,20));
	        l6.add(l5);
	        l6.add(t5);
	        
	        l7= new JLabel("Age");
	        l7.setBounds(50,300,100,30);
	        l7.setFont(new Font("Cambria",Font.BOLD,20));
	        l6.add(l7);

	        t6=new JTextField();
	        t6.setBounds(200,300,150,30);
	        l6.add(t6);

	        l8= new JLabel("Email");  
	        l8.setBounds(400,230,200,30);
	        l8.setFont(new Font("Cambria",Font.BOLD,20));
	        l6.add(l8);

	        t7=new JTextField();
	        t7.setBounds(600,230,150,30);
	        l6.add(t7);

	        b=new JButton("Submit");
	        b.setBounds(360,400,150,60);
	        b.setBackground(Color.BLACK);
	        b.setForeground(Color.WHITE);
	        l6.add(b);
	        b1=new JButton("<< Go Back");   
	        b1.setBackground(Color.BLACK);
	        b1.setForeground(Color.WHITE);
	        b1.setBounds(640,480,130,60);
	 
	        
	        b2=new JButton("Reset");   
	        b2.setBackground(Color.BLACK);
	        b2.setForeground(Color.WHITE);
	  
	        b2.setBounds(100, 480, 120, 60);
	        l6.add(b2);
	        l6.add(b1);
	        
	        b.addActionListener(new ActionListener()
	        	{
	        	public void actionPerformed(ActionEvent e) {
	        		try {
	        				ConnT c=new ConnT();
	    					String q="INSERT INTO details VALUES('"+t1.getText()+"','"+r+"','"+t3.getText()+ "','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+t7.getText()+"')";
	    					c.s.executeUpdate(q);
	    					JOptionPane.showMessageDialog(f,"Details Successfully Inserted");
	    	                f.setVisible(false);
	
	        				}catch(Exception e1) {System.out.println(e1.getMessage());
	       				}
	       			}});
	        b1.addActionListener(new ActionListener()
	        		{
	        		public void actionPerformed(ActionEvent e) {
	        			new Portal();
	        			f.setVisible(false);
	        		}
	        		});
	        b2.addActionListener(new ActionListener()
    		{
    		public void actionPerformed(ActionEvent e) {
    			t1.setText("");
    		//	t2.setText("");
    			t3.setText("");
    			t4.setText("");
    			t5.setText("");
    			t6.setText("");
    			t7.setText("");
    		}
    		});
	        
	f.setVisible(true);
	f.setDefaultCloseOperation(EXIT_ON_CLOSE);
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
       new Enroll();
	}

}
